export const articledata = {
    "plastic": {
      article: `Reduce: Minimize plastic usage by opting for alternatives and making conscious choices, such as:
  Choosing products with minimal or no plastic packaging.
  Bringing reusable bags, water bottles, and containers when shopping.
  Avoiding single-use plastics like straws, utensils, and plastic bags.
  Reuse: Extend the lifespan of plastic items by finding new uses for them, such as:
  Repurposing plastic containers for storage or organization.
  Using plastic bags as trash liners or for pet waste cleanup.
  Repurposing plastic bottles as planters, bird feeders, or storage containers.
  Recycle: Properly recycle plastic materials to divert them from landfills and promote their reuse in manufacturing processes, including:
  Separating plastic items from other waste and placing them in recycling bins.
  Following local recycling guidelines and ensuring plastics are clean and dry before recycling.
  Supporting initiatives and programs that promote plastic recycling and proper waste management practices.`,
      carbon: [0.8, 3.5],
      cost: 5 // Cost of recycling plastic in INR
    },
    "cardboard": {
      article: `Reduce: Minimize cardboard usage by opting for alternatives and making conscious choices, such as:
  Choosing products with minimal or no cardboard packaging.
  Selecting electronic statements and invoices over paper mail to reduce cardboard use in packaging.
  Considering digital alternatives for shipping materials, such as email or electronic documents.
  Reuse: Extend the lifespan of cardboard items by finding new uses for them, such as:
  Repurposing cardboard boxes for storage or moving purposes.
  Using cardboard tubes from paper towels or wrapping paper as organizers for cables, cords, or art supplies.
  Cutting and folding cardboard into DIY projects like homemade crafts or furniture.
  Recycle: Properly recycle cardboard materials to divert them from landfills and promote their reuse in manufacturing processes, including:
  Breaking down cardboard boxes and flattening them before placing them in recycling bins.
  Ensuring cardboard is clean and free of contaminants like food residue before recycling.
  Supporting local recycling programs and facilities that accept cardboard materials for recycling`,
      carbon: [0.6, 0.9],
      cost: 3 // Cost of recycling cardboard in INR
    },
    "trash": {
      article: `Reduce: Minimize the amount of trash generated by making conscious choices and opting for alternatives, such as:
  Avoiding single-use items and choosing reusable alternatives, like water bottles, bags, and containers.
  Purchasing products with minimal packaging or opting for products in bulk to reduce packaging waste.
  Planning meals to minimize food waste and composting organic waste when possible.
  Reuse: Extend the lifespan of items by finding new uses for them instead of discarding them, such as:
  Repurposing glass jars, plastic containers, and cardboard boxes for storage or organization.
  Donating items in good condition to local charities or thrift stores for reuse by others.
  Upcycling old furniture, clothing, or household items into new and creative projects.
  Recycle: Properly recycle materials to divert them from landfills and promote their reuse in manufacturing processes, including:
  Separating recyclable materials like paper, cardboard, plastic, glass, and metal from general waste.
  Following local recycling guidelines and ensuring materials are clean and sorted correctly before recycling.
  Supporting initiatives and programs that promote recycling and proper waste management practices in the community.`,
      carbon: [1, 5],
      cost: 7 // Cost of recycling trash in INR
    },
    "paper": {
      article: `Reduce: Minimize paper usage by opting for alternatives and making conscious choices, such as:
  Opting for electronic documents and communication whenever possible, like emails instead of printed letters.
  Printing on both sides of paper to reduce waste and conserve resources.
  Choosing digital platforms for note-taking, scheduling, and document storage to reduce the need for paper.
  Reuse: Extend the lifespan of paper items by finding new uses for them, such as:
  Using printed paper as scratch paper or for making notes before recycling.
  Repurposing paper packaging, like cardboard boxes and wrapping paper, for storage or crafts.
  Donating books, magazines, and newspapers to libraries, schools, or community centers for reuse by others.
  Recycle: Properly recycle paper materials to divert them from landfills and promote their reuse in manufacturing processes, including:
  Separating paper waste from other trash and placing it in designated recycling bins.
  Ensuring paper is clean and free of contaminants before recycling, removing staples or clips if necessary.
  Supporting local recycling programs and facilities that accept paper materials for recycling and promoting recycled paper products.`,
      carbon: [0.5, 1.5],
      cost: 4 // Cost of recycling paper in INR
    },
    "glass": {
      article: `Reduce: Minimize glass usage by opting for alternatives and making conscious choices, such as:
  Choosing products packaged in glass containers over plastic or other materials.
  Purchasing beverages in bulk or larger containers to reduce the amount of individual glass bottles or jars.
  Bringing reusable glass containers for shopping and storing bulk items instead of using single-use packaging.
  Reuse: Extend the lifespan of glass items by finding new uses for them, such as:
  Repurposing glass jars and bottles for storage of food, spices, or household items.
  Using glass containers as vases for flowers or decorative accents in home decor.
  Refilling glass bottles with homemade cleaners, condiments, or personal care products to reduce the need for new packaging.
  Recycle: Properly recycle glass materials to divert them from landfills and promote their reuse in manufacturing processes, including:
  Separating glass waste from other trash and placing it in designated recycling bins.
  Ensuring glass is clean and free of contaminants before recycling, removing lids and rinsing bottles and jars.
  Supporting local recycling programs and facilities that accept glass materials for recycling and promoting the use of recycled glass in new products.`,
      carbon: [0.2, 0.5],
      cost: 6 // Cost of recycling glass in INR
    },
    "metal": {
      article: `Reduce: Minimize metal usage by opting for alternatives and making conscious choices, such as:
  Choosing products with minimal metal packaging or packaging made from alternative materials.
  Selecting durable metal items that have a longer lifespan and require less frequent replacement.
  Avoiding single-use metal products and opting for reusable alternatives, like stainless steel water bottles instead of disposable ones.
  Reuse: Extend the lifespan of metal items by finding new uses for them instead of discarding them, such as:
  Repurposing metal containers, like cans and jars, for storage of food, craft supplies, or small household items.
  Refurbishing old metal furniture or fixtures to give them a new lease on life and prevent them from ending up in landfills.
  Donating unwanted metal items, such as appliances or utensils, to charitable organizations or individuals in need.
  Recycle: Properly recycle metal materials to divert them from landfills and promote their reuse in manufacturing processes, including:
  Separating metal waste from other trash and placing it in designated recycling bins or taking it to recycling centers.
  Ensuring metal items are clean and free of contaminants before recycling to improve the quality of recycled materials.
  Supporting local recycling programs and facilities that accept various types of metal for recycling and promoting the use of recycled metal in new products.`,
      carbon: [0.2, 0.8],
      cost: 8 // Cost of recycling metal in INR
    },
    "Mobile": {
      article: `Reduce: Extend the lifespan of your current mobile phone by using it for as long as possible before upgrading.
  Consider purchasing a refurbished or second-hand mobile phone instead of buying a brand new one.
  Choose mobile phones with eco-friendly features and materials, such as energy-efficient processors and recyclable components.
  Reuse: Donate your old mobile phone to charities, schools, or organizations that accept electronic donations.
  Repurpose your old mobile phone as a dedicated music player, alarm clock, or remote control.
  Use your old mobile phone as a backup device for emergencies or travel.
  Recycle: Take your old mobile phone to designated electronic waste recycling centers or drop-off locations.
  Utilize trade-in programs offered by mobile phone retailers to recycle your old device when purchasing a new one.
  Remove and recycle the battery separately from the rest of the phone to ensure proper disposal and recycling.`,
      carbon: [85, 95],
      cost: 200 // Cost of recycling a mobile phone in INR
    },
    "Keyboard": {
      article: `Reduce: Opt for durable and high-quality keyboards that have a longer lifespan to reduce the frequency of replacements.
  Choose wireless or Bluetooth keyboards to minimize the use of cables and reduce electronic waste.
  Consider using keyboard covers or protective cases to prevent damage and extend the lifespan of your keyboard.
  Reuse: Donate your old keyboard to schools, community centers, or non-profit organizations for reuse by others.
  Repurpose your old keyboard as a spare or backup device for emergencies or temporary use.
  Use individual keys from old keyboards for craft projects or DIY projects, such as keychains or jewelry.
  Recycle: Take your old keyboard to electronic waste recycling centers or drop-off locations for proper disposal.
  Look for recycling programs offered by electronic retailers or manufacturers to recycle keyboards and other electronic devices.
  Disassemble the keyboard and separate recyclable materials, such as plastic keycaps and metal components, for recycling.`,
      carbon: [1, 10],
      cost: 50 // Cost of recycling a keyboard in INR
    },
    "Mouse": {
      article: `Reduce: Opt for durable and high-quality mice that have a longer lifespan to reduce the frequency of replacements.
  Choose wireless or Bluetooth mice to minimize the use of cables and reduce electronic waste.
  Turn off or unplug your mouse when not in use to conserve energy and extend its lifespan.
  Reuse: Donate your old mouse to schools, community centers, or non-profit organizations for reuse by others.
  Repurpose your old mouse as a spare or backup device for emergencies or temporary use.
  Use individual parts or components from old mice for DIY projects or repairs.
  Recycle: Take your old mouse to electronic waste recycling centers or drop-off locations for proper disposal.
  Look for recycling programs offered by electronic retailers or manufacturers to recycle mice and other electronic devices.
  Disassemble the mouse and separate recyclable materials, such as plastic shells and metal components, for recycling.`,
      carbon: [1, 10],
      cost: 40 // Cost of recycling a mouse in INR
    },
    "Battery": {
      article: `Reduce: Use rechargeable batteries instead of single-use ones to minimize battery waste and reduce environmental impact.
  Opt for devices that have built-in rechargeable batteries or can be powered by renewable energy sources.
  Turn off or unplug electronic devices when not in use to conserve battery power and extend battery life.
  Reuse: Recharge and reuse rechargeable batteries multiple times before disposing of them.
  Use old batteries in low-drain devices like remote controls, clocks, or LED flashlights to give them a second life.
  Donate functioning but no longer needed batteries to community centers, schools, or charities for reuse in less critical applications.
  Recycle: Recycle old batteries at designated collection points or drop-off locations to prevent hazardous materials from entering landfills.
  Look for battery recycling programs offered by electronic retailers, manufacturers, or local government agencies.
  Properly dispose of batteries according to local regulations and guidelines to ensure safe handling and recycling.`,
      carbon: [1, 10],
      cost: 20 // Cost of recycling a battery in INR
    }
  };